//
// Created by Reza Alizadeh Majd on 2018-12-23.
//

#ifndef PX_ACCOUNTS_SERVICE_TEST_COMMON_H
#define PX_ACCOUNTS_SERVICE_TEST_COMMON_H

#define SERVER_ADDRESS "127.0.0.1:1234"


#endif //PX_ACCOUNTS_SERVICE_TEST_COMMON_H
