//
// Created by Reza Alizadeh Majd on 9/11/19.
//

#ifndef PX_ACCOUNTS_SERVICE_ACCOUNTOBJECT_H
#define PX_ACCOUNTS_SERVICE_ACCOUNTOBJECT_H

#include <Utils/ErrorReporter.h>
#include <Utils/Utils.h>

#include "AccountService.h"

/// @brief Object holding Account details
class AccountObject : public ErrorReporter {
   public:
    explicit AccountObject();

    /// @brief verify Account
    bool verify();

    /// @brief cleanup old account stuff which are not required for new definition
    bool cleanup(const AccountObject &newAccount);

    /// @brief remove custom assets generated by account services
    bool performAccountRemoval();

    string idAsString() const { return uuid_as_string(this->id); }

    bool setId(const string &strId) { return uuid_from_string(strId, this->id); }

    inline bool isIdSet() const { return uuid_is_null(this->id) == 0; }

    bool hasService(const string &svcName) const; 

   protected:
    /// @brief update params related to defined provider for AccountObject
    bool _appendProviderParams();

   public:
    uuid_t id;                             ///< @brief unique id assigned to account
    string title;                          ///< @brief title of account
    string provider;                       ///< @brief defined Provider for account
    bool is_active;                        ///< @brief shows whether the account is active or not
    StrStrMap settings;                    ///< @brief Key-Value Map of settings related to an account
    map<string, AccountService> services;  ///< @brief Map of Services defined inside an account

    bool is_readonly;
    string path;
};

#endif  // PX_ACCOUNTS_SERVICE_ACCOUNTOBJECT_H
